spring.application.name=sever


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BeeLapTopp;encrypt=true;trustServerCertificate=true;

spring.datasource.username=sa
spring.datasource.password=kien2310
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
#server.servlet.context-path=/api
#
jwt.secret=jc49yrwFmdu+mZwMkNR4/Z504kb77L6tDf+FM8b2bUu7awh4D1tQayV5pLXjFa7
jwt.expiration=86400 
jwt.expiration.refresh=1209600 

REACT_APP_API_URL=http://localhost:8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=770138942844-q2l5f5us92bs98d65jk8r5knhuqp9n47.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
# C?u hình email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trikien2310@gmail.com
spring.mail.password=fznj ysyg blud aypq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


app:
order:
online:
hold:
vnpay-minutes: 15
cod-hours: 24

app.order.online.hold.enabled=false

vnpay.tmn-code=D8QUX84H
vnpay.secret-key=Z7SH4S6IER48057R2R3ENI17PRJ04Q5Z
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/pos/payment/vnpay-return
vnpay.order-type=other
vnpay.locale=vn

# ===== MOMO =====
momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
# endpoint nên là API create payment v2
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=http://localhost:8080/api/pos/payment/momo-return
momo.notify-url=http://localhost:8080/api/pos/payment/momo-ipn


ghn.base-url=https://online-gateway.ghn.vn/shiip/public-api
ghn.token=7d67a984-b5fe-11ef-b166-4205c1d15e61
ghn.shop-id=5511482

# ??a ch? shop (?i?m l?y hàng)
ghn.from-district-id=1492
ghn.from-ward-code=1A0501

# m?c ??nh service type
ghn.service-type-id=2

#CLOUDINARY_URL=${CLOUDINARY_URL:gH2O0iAgA6_2kQWar8ibAh6PGo0}
CLOUDINARY_URL=cloudinary://431774439172648:gH2O0iAgA6_2kQWar8ibAh6PGo0@dnqgxcmzz

